---
title: "My map"
author: "Alessandro"
date: "11/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## November 17 2020
```{r , echo=FALSE}
library(leaflet)

my_town <- data.frame(name = c("Modena","Formigine","Spilamberto","Nonantola","Castel_N_Rang","Maranello",
   "Sassuolo","Castelfranco"),
   pop = c(186000,34000,12800,16100,15100,17600,40800,33000),
   latit = c(44.642769,44.5746005,44.5327877,44.675884,44.552372,44.525551,
             44.540367,44.594810),
   long = c(10.918670,10.8470242,11.0224297,11.035259,10.936111,10.866323,
            10.782540,11.053393),
   color = c("red","blue","green","green","green","green",
             "blue","blue"), stringsAsFactors = FALSE)

legcol <- data.frame(labels = c("pop = 186k",
                    "33k < pop < 41k","12.8k < pop < 17.6k"),
                    color = c("red","blue","green"), 
                    stringsAsFactors = FALSE)


latit <- c(44.642769,44.6520131,44.5313315)
long <- c(10.918670, 10.9366486,10.8726192)
labels <- c("This is Modena: my town", "Enzo Ferrari museum", "Ferrari company")

my_map <- leaflet() %>%
    addTiles() %>%
    addMarkers(lat = latit,lng = long, popup = labels) %>%
    addCircles(lat = my_town$latit, lng = my_town$long, 
               radius = sqrt(my_town$pop)*8, 
            popup = my_town$name,weight = 1, 
            color = my_town$color) %>%
    addLegend(labels = legcol$labels, colors = legcol$color)

my_map

```
